# Generated by Django 3.1.7 on 2021-02-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack_choice', models.CharField(choices=[('FE', 'Frontend'), ('BE', 'Backend'), ('BB', 'Both')], max_length=2)),
                ('programming_languages', models.CharField(choices=[('0', '0'), ('1-2', '1-2'), ('3-4', '3-4'), ('5-6', '5-6'), ('7+', '7+')], max_length=3)),
                ('programming_exp', models.IntegerField()),
                ('database_exp', models.CharField(choices=[('PG', 'PostgreSQL'), ('MS', 'MySQL'), ('OR', 'Oracle'), ('SS', 'SQL Server')], max_length=2)),
            ],
        ),
    ]
